export default {
  sv: {
    music: "Musik",
    score: "Noter",
    back: "← Tillbaka till innehåll",
    audioFallback: "Din webbläsare stöder inte ljuduppspelning.",
    after: "Efter",
    by: "av",
    translation: "Översättning",
    meter: "Versmått",
    languageLabel: "Språk",
    home: "Innehåll",
    backToHymn: "Tillbaka till sången",
    showScore: "Visa noter",
    translationNotice: "",
  },
  en: {
    music: "Music",
    score: "Score",
    back: "← Back to index",
    audioFallback: "Your browser does not support audio playback.",
    after: "After",
    by: "by",
    translation: "Translation",
    meter: "Meter",
    languageLabel: "Language",
    home: "Index",
    backToHymn: "Back to hymn",
    showScore: "Show score",
    translationNotice: "This is a translation of the Swedish lyrics and cannot be sung.",
  },
  fr: {
    music: "Musique",
    score: "Partition",
    back: "← Retour au sommaire",
    audioFallback: "Votre navigateur ne prend pas en charge la lecture audio.",
    after: "D’après",
    by: "de",
    translation: "Traduction",
    meter: "Mètre",
    languageLabel: "Langue",
    home: "Sommaire",
    backToHymn: "Retour au cantique",
    showScore: "Voir la partition",
    translationNotice: "Ceci est une traduction des paroles suédoises et ne peut pas être chantée.",
  },
  ar: {
    music: "الموسيقى",
    score: "النوتة",
    back: "← العودة إلى الفهرس",
    audioFallback: "متصفحك لا يدعم تشغيل الصوت.",
    after: "بعد",
    by: "بواسطة",
    translation: "ترجمة",
    meter: "الوزن",
    languageLabel: "اللغة",
    home: "الفهرس",
    backToHymn: "العودة إلى الترنيمة",
    showScore: "عرض النوتة",
    translationNotice: "هذه ترجمة للنص السويدي ولا يمكن غناؤها.",
    translationNoticeMachine: "الترجمة مولَّدة آلياً وقد تحتوي على أخطاء.",
  },
  es: {
    music: "Música",
    score: "Partitura",
    back: "← Volver al índice",
    audioFallback: "Tu navegador no admite la reproducción de audio.",
    after: "Según",
    by: "de",
    translation: "Traducción",
    meter: "Métrica",
    languageLabel: "Idioma",
    home: "Índice",
    backToHymn: "Volver al cántico",
    showScore: "Ver la partitura",
    translationNotice: "Esta es una traducción del texto sueco y no se puede cantar.",
    translationNoticeMachine: "La traducción se ha generado automáticamente y puede contener errores.",
  },
};
